# fly.toml app configuration file generated for fpb-calendar on 2025-02-06T19:25:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fpb-calendar'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = "1h"     # Run health checks every 1 hour
    timeout = "5s"       # Fail if no response in 2 seconds
    grace_period = "60s" # Wait 10 seconds after app starts before checking
    method = "GET"       # Use GET HTTP method
    path = "/health"     # Health check endpoint
    protocol = "http"    # Use HTTP
    headers = { Host = "fpb-calendar.fly.dev" } # Optional: Add Host header
    tls_skip_verify = false

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
